behind_bungee: false
essence:
  scanInterval: 30s
  delay: 30m
  restInterval: 22h
  bonus:
   message: ~1You have returned for %days% days, here is some bonus essence!
   factors:
    2: 2.0
    7: 2.0
    30: 2.0
  message: ~1Welcome back, enjoy your advent prize!
  # use %player% to inject player name. The command is run as Console.
  command: 'cc give virtual cosmic 1 %player%'
  dropMessage: ~1Failed to give you your advent prize, please let Bonkill or DeepCopy know.
database:
 host:
 port:
 database_name:
 user:
 password:
